name: CI/CD

on:
  push:
    branches:
      - "master"
    paths:
      - "static/img/collaborators/*"
      - "static/img/members/*"
      - "data/**"
      - "i18n/**"
      - "content/**"
      - "layouts/**"
      - "src/**"
      - "static/js/*"
      - "config.toml"
  workflow_dispatch:

jobs:
  build:
    name: Build & deploy website
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # you must check out the repository
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Checkout gh-pages branch on subfolder
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: .gh-pages
      # setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      # install node dependencies
      - run: npm i
      # compile
      - run: npm run compile:css
      - name: hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          version: 0.62.2
          image: alpine
          env: production
      # BUG: the checkout action token cannot launch gh-pages building process, only uploading files
      # https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true
      - name: Configure CI credentials
        run: ./bin/configure-ci
      - name: deploy
        run: ./bin/deploy
